<?php

declare(strict_types=1);

use Cv\Form\CvForm;
use Cv\Entity\Cv;

$this->headTitle('Submit a new CV');

/** @var CvForm $form */
$form    = $this->form;
$error   = $this->error;
$success = $this->success;

$name      = $form->get(Cv::NAME)->setAttribute('class', 'form-control');
$email     = $form->get(Cv::EMAIL)->setAttribute('class', 'form-control');
$telephone = $form->get(Cv::TELEPHONE)->setAttribute('class', 'form-control');
$position  = $form->get(Cv::POSITION)->setAttribute('class', 'form-control');
$education = $form->get(Cv::EDUCATION)->setAttribute('class', 'form-control');
$comments  = $form->get(Cv::COMMENTS)->setAttribute('class', 'form-control');
$file      = $form->get(Cv::FILE)->setAttribute('class', 'form-control');
$submit    = $form->get('submit')->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('send-cv', ['action' => 'send']));
$form->prepare();

$validationErrorAttributes = ['class' => 'alert alert-danger', 'style' => 'list-style-type:none;'];

?>
<?php if (isset($error)) { ?>
    <div class="alert alert-danger" role="alert">
        <?= $error ?>
    </div>
<?php } ?>
<?php if (isset($success)) { ?>
    <div class="alert alert-success" role="alert">
        <?= $success ?>
    </div>
<?php } ?>
<div class="jumbotron">
    <?= $this->form()->openTag($form); ?>
    <div class="form-group">
        <?= $this->formLabel($name) ?>
        <?= $this->formElement($name) ?>
        <?= $this->formElementErrors()->render($name, $validationErrorAttributes) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($email) ?>
        <?= $this->formElement($email) ?>
        <?= $this->formElementErrors()->render($email, $validationErrorAttributes) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($telephone) ?>
        <?= $this->formElement($telephone) ?>
        <?= $this->formElementErrors()->render($telephone, $validationErrorAttributes) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($position) ?>
        <?= $this->formElement($position) ?>
        <?= $this->formElementErrors()->render($position, $validationErrorAttributes) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($education) ?>
        <?= $this->formElement($education) ?>
        <?= $this->formElementErrors()->render($education, $validationErrorAttributes) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($comments) ?>
        <?= $this->formElement($comments) ?>
        <?= $this->formElementErrors()->render($comments, $validationErrorAttributes) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($file) ?>
        <?= $this->formElement($file) ?>
        <?= $this->formElementErrors()->render($file, $validationErrorAttributes) ?>
    </div>

    <div class="float-right">
        <input class="btn btn-danger" type="reset" value="Reset fields">
        <?= $this->formSubmit($submit); ?>
    </div>

    <?= $this->formHidden($form->get(Cv::ID)); ?>
    <?= $this->form()->closeTag(); ?>

</div>